"""replace holdings with asset transaction ledger

Revision ID: 9786719007f1
Revises: db7cc8537542
Create Date: 2026-09-12 23:03:50.470266

Data migration note: each pre-existing `holdings` row (a single manually
entered quantity + avg_buy_price, no history) is backfilled into one opening
"buy" `asset_transactions` row dated at its `created_at`. The real historical
exchange rate used at holding-creation time was never recorded anywhere, so
`amount_base_currency`/`exchange_rate` are reconstructed best-effort: 1 for
same-currency, else the closest `exchange_rates` row cached on/before that
date, else 1. Fine for a one-time personal-DB backfill; not a general
reconciliation.
"""
from decimal import Decimal
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9786719007f1'
down_revision: Union[str, Sequence[str], None] = 'db7cc8537542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _backfill_asset_transactions_from_holdings(bind) -> None:
    holdings = bind.execute(
        sa.text(
            """
            SELECT h.account_id, h.asset_id, h.quantity, h.avg_buy_price, h.created_at,
                   a.currency AS asset_currency, u.base_currency AS user_base_currency
            FROM holdings h
            JOIN accounts acc ON acc.id = h.account_id
            JOIN assets a ON a.id = h.asset_id
            JOIN users u ON u.id = acc.user_id
            """
        )
    ).mappings().all()

    for row in holdings:
        trade_date = row["created_at"].date()
        if row["asset_currency"] == row["user_base_currency"]:
            rate = Decimal("1")
        else:
            cached_rate = bind.execute(
                sa.text(
                    """
                    SELECT rate FROM exchange_rates
                    WHERE from_currency = :from_currency AND to_currency = :to_currency
                      AND date <= :on_date
                    ORDER BY date DESC LIMIT 1
                    """
                ),
                {
                    "from_currency": row["asset_currency"],
                    "to_currency": row["user_base_currency"],
                    "on_date": trade_date,
                },
            ).scalar()
            rate = Decimal(str(cached_rate)) if cached_rate is not None else Decimal("1")

        quantity = Decimal(str(row["quantity"]))
        price = Decimal(str(row["avg_buy_price"]))

        bind.execute(
            sa.text(
                """
                INSERT INTO asset_transactions
                    (id, account_id, asset_id, type, quantity, price, fee,
                     amount_base_currency, exchange_rate, date, notes, created_at)
                VALUES
                    (gen_random_uuid(), :account_id, :asset_id, 'buy', :quantity, :price, 0,
                     :amount_base_currency, :exchange_rate, :trade_date, :notes, :created_at)
                """
            ),
            {
                "account_id": row["account_id"],
                "asset_id": row["asset_id"],
                "quantity": quantity,
                "price": price,
                "amount_base_currency": quantity * price * rate,
                "exchange_rate": rate,
                "trade_date": trade_date,
                "notes": "Migrato da una posizione inserita manualmente (avg_buy_price)",
                "created_at": row["created_at"],
            },
        )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('amount_base_currency', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type in ('buy','sell')", name='ck_asset_transactions_type'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_transactions_account_id'), 'asset_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_asset_transactions_asset_id'), 'asset_transactions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_transactions_date'), 'asset_transactions', ['date'], unique=False)
    # ### end Alembic commands ###

    _backfill_asset_transactions_from_holdings(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holdings_account_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_asset_id'), table_name='holdings')
    op.drop_table('holdings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=24, scale=8), autoincrement=False, nullable=False),
    sa.Column('avg_buy_price', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('holdings_account_id_fkey')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('holdings_asset_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('holdings_pkey')),
    sa.UniqueConstraint('account_id', 'asset_id', name=op.f('uq_holdings_account_asset'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_holdings_asset_id'), 'holdings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_holdings_account_id'), 'holdings', ['account_id'], unique=False)
    op.drop_index(op.f('ix_asset_transactions_date'), table_name='asset_transactions')
    op.drop_index(op.f('ix_asset_transactions_asset_id'), table_name='asset_transactions')
    op.drop_index(op.f('ix_asset_transactions_account_id'), table_name='asset_transactions')
    op.drop_table('asset_transactions')
    # ### end Alembic commands ###
